### ISSUE TITLE
Activity 4.1.2 Hash Tables: Context, Visuals

### ISSUE THREAD

**Issue by taimurkashif** [bitprj/curriculum#123]
**2.md**

* Give an explanation of why you can access element in O(1) time
* In step 1 of hashing, elaborate on the line "this element can be used as an index to store the original element."
* Explain _why_ modulo is a good way to reduce the hash to an index
* Provide explanation for the diagram. At this point, the reader has no context to what a diagram of a hash table looks like, so the diagram may be confusing without further explanation as to what the numbers on the right are, what an "item" is, why there are arrows between items, why some slots have items and some don't, etc.

**Comment by bitscott1102** [comment]
1. It's O(1) because the amount of time does not change with the size of the collection. 

2. An element is converted into an integer by using a hash function. This element can be used as an index to store the original element, which falls into the hash table.

- The item that is in index 0 is converted into an integer and 01 represents that.

3.  which modulo? 

4. We distribute items through a hashing function. If the items are assigned with index 0 then, it will be connected with 0. Items could be linked together. For index 5, three items are linked together.
